---
# Setup/install tasks.
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Ensure rabbitmq is started and enabled (if configured).
  service:
    name: "{{ rabbitmq_daemon }}"
    state: "{{ rabbitmq_state }}"
    enabled: "{{ rabbitmq_enabled }}"

- name: Enables the rabbitmq_management plugin
  rabbitmq_plugin:
    names: rabbitmq_management
    state: enabled

- rabbitmq_user:
     user: "{{rabbitmq_usr}}"
     password: "{{rabbitmq_pwd}}"
     tags: "admin,administrator"
     state: present
     vhost: /
     configure_priv: .*
     read_priv: .*
     write_priv: .*    
