---
- name: Erlang Repo RPM install with yum
  yum: name=https://packages.erlang-solutions.com/erlang/rpm/centos/7/x86_64/esl-erlang_23.3.1-1~centos~7_amd64.rpm

- name: Add packagecloud GPG key.
  rpm_key:
    key: "https://packagecloud.io/gpg.key"
    state: present

- name: Download RabbitMQ package.
  get_url:
    url: "{{ rabbitmq_rpm_url }}"
    dest: "/tmp/{{ rabbitmq_rpm }}"

- name: Ensure RabbitMQ is installed.
  yum:
    name: "/tmp/{{ rabbitmq_rpm }}"
    state: "present"
